### ISSUE TITLE
chore: README.md 작성하기

### ISSUE THREAD

**Issue by min3eo** [mun-jihye/rolling-paper-app#108]
## Description
리드미 작성을 위한 이슈입니다.

## Todo
- [x] 상단 이미지
- [ ] 배포주소
- [x] 프로젝트에 대한 소개
- [x] 사용한 기술 스택
- [x] 주요 기능
- [x] 서비스 구성 
- [x] 팀 소개

- [x] 페이지 상세 설명
- [x] 이쁘게 꾸미기

## ETC
기타 사항
