### ISSUE TITLE
feat: Badge 컴포넌트 구현

### ISSUE THREAD

**Issue by mun-jihye** [mun-jihye/rolling-paper-app#26]
## Description
Badge 컴포넌트 구현하기
## Todo
- [x] Badge 파일 생성
- [x] Badge 디자인
- [x] emoji badge component
- [x] profile badge component
## ETC
기타 사항
