### ISSUE TITLE
feat: EditPage UI 및 헤더 구현하기

### ISSUE THREAD

**Issue by mun-jihye** [mun-jihye/rolling-paper-app#59]
## Description
edit page UI 구현하기
## Todo

- [x] 카드 목록은 '최신순'으로 무한 스크롤 방식으로 배치합니다.
- [x] '카드'를 누르면 해당 카드가 확대되어 보여집니다.
- [x] PC에서 헤더 영역의 너비는 1200px로 고정하고 좌우 여백만 변하다가, 화면의 너비가 1248px보다 줄어들 때 좌우 여백은 24px로 고정하고 'To.OOO' 영역과 '프로필 이미지 OO명이 작성 했어요!' 영역이 가까워집니다.
- [x] PC에서 카드 목록 영역의 너비는 1200px로 고정하고 좌우 여백만 변하다가, 화면의 너비가 1248px보다 줄어들 때 좌우 여백은 24px로 고정하고 카드들의 너비가 줄어듭니다.
- [x] 저장된 이모지는 횟수가 많은 순서대로 최대 '8개' 까지 나열해 주세요.
- [x] 카카오톡 공유 docs를 참고해 '카카오톡 공유' 기능을 만들어 주세요. (구현 방법이나 공유에 들어갈 메시지는 팀 내에서 논의해 결정해 주세요)
- [x] 'URL 공유'를 클릭하면 클립보드에 URL을 저장하고, URL이 복사되었다는 토스트를 5초 동안 보였다가 사라지게 해주세요.
- [x] 이모지 추가 드롭다운 디자인은 예시이고, 이와 동일한 기능을 하는 외부 모듈의 디자인을 그대로 사용해도 좋습니다.
- [x] '+' 버튼을 누르면 /post/{id}/message 로 이동합니다.
- [x] 반응형 적용하기

## ETC
기타 사항
