### ISSUE TITLE
feat: EditPage 내 카드 컴포넌트 데이터 연동하기

### ISSUE THREAD

**Issue by mun-jihye** [mun-jihye/rolling-paper-app#66]
## Description
카드 컴포넌트 데이터 넘기기 및 디자인
## Todo
- [x] post/{id}를 통해 사용자의 아이디에 맞는 롤링페이퍼를 get요청으로 불러온다.
- [x] 편집하기 버튼을 만들고 편집하기를 누르면 삭제 쓰레기통 버튼과 삭제하기 버튼이 보인다.
- [x] 삭제하기 버튼을 누르면 전체 데이터가 삭제되고 쓰레기통 버튼을 누르면 해당 카드만 삭제된다.
- [x] 데이터가 없을 경우 추가하기 카드만 있고 첫 데이터는 기본적으로 추가하기 카드가 있다.
- [x] 삭제하기 모드에서는 추가하기 카드가 없다. 
- [x] 배경은 서버에서 받아온 이미지나 배경 색을 적용한다.
## ETC
기타 사항
